# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: false # May lead to unexpectedly aborted goals with scaled JTC
# moveit_simple_controller_manager:
controller_names:
  - mcx_arm_controller

mcx_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - pr15_shoulder_pan_joint
    - pr15_shoulder_lift_joint
    - pr15_elbow_joint
    - pr15_wrist1_joint
    - pr15_wrist2_joint
    - pr15_wrist3_joint
