controller_manager:
  ros__parameters:
    update_rate: 100

    mcx_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mcx_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


mcx_arm_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    
    joints:
      - pr15_shoulder_pan_joint
      - pr15_shoulder_lift_joint
      - pr15_elbow_joint
      - pr15_wrist1_joint
      - pr15_wrist2_joint
      - pr15_wrist3_joint


    state_publish_rate: 125.0
    action_monitor_rate: 100.0
    allow_integration_in_goal_trajectories: true

    gains:
      pr15_shoulder_pan_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0

      pr15_shoulder_lift_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0
      
      pr15_elbow_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0

      pr15_wrist1_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0

      pr15_wrist2_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0

      pr15_wrist3_joint:
        p: 10.0
        i: 1.0
        d: 0.5
        i_clamp: 0.0
        ff_velocity_scale: 1.0


    open_loop_control: false
    allow_partial_joints_goal: true
