controller_manager:
  ros__parameters:
    update_rate: 100

    mcx_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mcx_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


mcx_arm_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6


    state_publish_rate: 125.0
    action_monitor_rate: 100.0
    allow_integration_in_goal_trajectories: true

    gains:
      Joint1:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0

      Joint2:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
      
      Joint3:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0

      Joint4:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0

      Joint5:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0

      Joint6:
        p: 5.0
        i: 1.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0


    open_loop_control: true
    allow_partial_joints_goal: false
    set_last_command_interface_value_as_state_on_activation: true

